package com.example.maks.notes.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.maks.notes.database.NoteData;

import com.example.maks.notes.database.NoteDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDataDaoConfig;

    private final NoteDataDao noteDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDataDaoConfig = daoConfigMap.get(NoteDataDao.class).clone();
        noteDataDaoConfig.initIdentityScope(type);

        noteDataDao = new NoteDataDao(noteDataDaoConfig, this);

        registerDao(NoteData.class, noteDataDao);
    }
    
    public void clear() {
        noteDataDaoConfig.getIdentityScope().clear();
    }

    public NoteDataDao getNoteDataDao() {
        return noteDataDao;
    }

}
