package com.example.maks.notes.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NOTE_DATA".
 */
public class NoteData {

    private String objectId;
    private String ownerId;
    /** Not-null value. */
    private String title;
    private String description;
    private String note_date;
    private java.util.Date updated;
    private java.util.Date created;
    private String deleted;

    public NoteData() {
    }

    public NoteData(String objectId) {
        this.objectId = objectId;
    }

    public NoteData(String objectId, String ownerId, String title, String description, String note_date, java.util.Date updated, java.util.Date created, String deleted) {
        this.objectId = objectId;
        this.ownerId = ownerId;
        this.title = title;
        this.description = description;
        this.note_date = note_date;
        this.updated = updated;
        this.created = created;
        this.deleted = deleted;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getOwnerId() {
        return ownerId;
    }

    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getNote_date() {
        return note_date;
    }

    public void setNote_date(String note_date) {
        this.note_date = note_date;
    }

    public java.util.Date getUpdated() {
        return updated;
    }

    public void setUpdated(java.util.Date updated) {
        this.updated = updated;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public String getDeleted() {
        return deleted;
    }

    public void setDeleted(String deleted) {
        this.deleted = deleted;
    }

}
